services:
  _defaults:
    autowire: true

  D3\OxidTwigExtensions\MethodExistsExtension:
    tags: ['twig.extension']

  D3\OxidTwigExtensions\ModuleSettingsServiceExtension:
    tags: ['twig.extension']

  D3\OxidTwigExtensions\ShopConfigurationExtension:
    tags: ['twig.extension']