services:
  _defaults:
    autowire: true

  D3\OxidTwigExtensions\MethodExistsExtension:
    tags: ['twig.extension']

  D3\OxidTwigExtensions\ModuleSettingsServiceExtension:
    tags: ['twig.extension']

  D3\OxidTwigExtensions\ShopConfigurationExtension:
    tags: ['twig.extension']

#  requires intl extension
#  Jasny\Twig\DateExtension:
#    tags: ['twig.extension']

  Jasny\Twig\PcreExtension:
    tags: ['twig.extension']

  Jasny\Twig\TextExtension:
    tags: [ 'twig.extension' ]

  Jasny\Twig\ArrayExtension:
    tags: [ 'twig.extension' ]